name: Create Main Zip and Release

on:
  push:
    branches:
      - main

jobs:
  zip_and_release:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Create Zip File
        run: |
          zip -r main.zip . -x "*.git*" -x "main.zip"
      - name: Delete Previous Release (if exists)
        uses: larryjoelane/delete-release-action@v1.0.24
        with:
          tag: v1.0.0  # Specify the tag of the release to delete
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }} 
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }} 
        with:
          tag_name: v1.0.0
          release_name: Release v1.0.0
          draft: false
          prerelease: false
      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./main.zip
          asset_name: main.zip
          asset_content_type: application/zip
